"""empty message

Revision ID: 8183ccc26491
Revises: 
Create Date: 2025-06-28 18:46:42.853026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8183ccc26491'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('count_questions', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('variant_1', sa.String(length=100), nullable=False),
    sa.Column('variant_2', sa.String(length=100), nullable=True),
    sa.Column('variant_3', sa.String(length=100), nullable=True),
    sa.Column('variant_4', sa.String(length=100), nullable=True),
    sa.Column('variant_5', sa.String(length=100), nullable=True),
    sa.Column('correct_answer', sa.JSON(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redeem_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz', sa.Integer(), nullable=True),
    sa.Column('code_enter', sa.Integer(), nullable=True),
    sa.Column('hosted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hosted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['quiz'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who_passed', sa.Integer(), nullable=True),
    sa.Column('what_passed', sa.Integer(), nullable=True),
    sa.Column('right_answers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['what_passed'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['who_passed'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('redeem_code')
    op.drop_table('question')
    op.drop_table('quiz')
    op.drop_table('user')
    # ### end Alembic commands ###
